name: blackglowstudio
favicon: null
layout_spectrum: 0.45371008734218776
typography_spectrum: 0.7641736587975174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6250331345945597
  lightness: 0.39570629270747304
  saturation: 0.9132388250436634
  rhythmicContrast: 0.7178955655544996
purpose: []
